#!/usr/bin/python

import sys
import re
import getopt

debug = False

def log(msg):
    if debug == True:
        print msg

def pprint(obj):
    if debug:
        import pprint
        pp = pprint.PrettyPrinter(indent=1)
        pp.pprint(obj)

def build_graph(file):

    graph = {}

    f = open(file)
    n = int(f.readline())
    for _ in xrange(n):
        line = f.readline().rstrip()

        # Load the accuser and the number of people accused by him/her
        (accuser, strnumaccusasions) = re.split('\s+', line)
        numaccusations = int(strnumaccusasions)

        if(not graph.has_key(accuser)):
            graph[accuser]={}
        accused = graph[accuser]

        for num in xrange(numaccusations):
            accusee = f.readline().rstrip()
            accused[accusee] = True
            if(graph.has_key(accusee)):
                graph[accusee][accuser]=True
            else:
                graph[accusee] = { accuser: True }

    f.close
    return graph

def partitions(graph):

    graphlen = len(graph)

    g1 = set([])
    g2 = set([])
    if(graphlen == 0):
        return [len(g1),len(g2)]

    current_nodes = []
    next_nodes = []

    visited = {}
    current_nodes.append( graph.keys()[0] )
    visited[current_nodes[0]] = True
    flag = True

    while(len(g1) + len(g2) < graphlen):
        next_nodes = []
        for p in current_nodes:
            if(flag):
                g1.add(p)
            else:
                g2.add(p)
            for k in graph[p]:
                if(not visited.has_key(k)):
                    next_nodes.append(k)
                visited[k] = True
            visited[p]= True
        current_nodes = next_nodes
        flag = not flag

    log(g1)
    log(g2)

    return [len(g1),len(g2)]

def main():
    """Main function"""

    # I'm using -d to enable debug
    try:
        opts, args = getopt.getopt(sys.argv[1:], "d")
    except getopt.GetoptError:
        sys.exit(2)
    for o, v in opts:
        if (o == "-d"):
            global debug
            debug = True

    # load the input file
    # into memory using a dictionary (aka hash)
    graph = build_graph(args[0])
    pprint(graph)

    # do the hard part, finding the 2 partitions
    # into the graph, this is basically a visit
    # algorithm 
    (g1, g2) = partitions(graph)

    # print the result
    if(g1>=g2):
        print "%d %d" % (g1,g2)
    else:
        print "%d %d" % (g2,g1)

if __name__ == "__main__":
    main()
