#!/usr/bin/env python

import sys
import re

def log(msg):
    print msg

def read_node(f):
    line = f.readline().rstrip()
    if line == "":
        return 0
    (name, strcount) = re.split('\s+', line)
    count = int(strcount)
    liars = []
    while(count>0):
        liars.append(f.readline().rstrip())
        count-=1
    return (name, liars)

def read(file):
    f = open(file)
    total_people = int(f.readline())
    log("total: " + str(total_people))
    accusations = []
    while(1):
        node = read_node(f)
        if node == 0:
            break
        accusations.append(node)
    f.close
    return accusations

def solve(accusations):
    pass

def main():
    accusations = read(sys.argv[1])
    log(accusations)
    solve(accusations)

if __name__ == "__main__":
    main()
