#!/usr/bin/python

import sys
import getopt
import re

debug = False

def log(msg):
    if debug == True:
        print msg

def pprint(obj):
    if debug:
        import pprint
        pp = pprint.PrettyPrinter(indent=1)
        pp.pprint(obj)

def load_input(file):

    data = []
    
    try:
        f = open(file)
        W = f.readline().rstrip() 

        for line in f:
            # data structure will be in format of list of listes
            # each element of the list is of this format:
            # (SKU, weight, cost)
            data.append( re.split('\s+', line.rstrip()) )

        f.close()
    except Exception as e:
        print e
        sys.exit(2)

    return (data, W)

def main():
    """Main function"""

    # I'm using -d to enable debug
    try:
        opts, args = getopt.getopt(sys.argv[1:], "d")
    except getopt.GetoptError:
        sys.exit(2)
    for o, v in opts:
        if (o == "-d"):
            global debug
            debug = True
   
    file = ""
    W = 0
    try:
        if(args[0]):
            file = args[0]
        (data, W) = load_input(file)
        log("Max weight (W): " + W)
        pprint(data)
    except IndexError:
        print "Provide input file"
        sys.exit(2)

if __name__ == "__main__":
    main()
